### ISSUE TITLE
请问怎么部署啊

### ISSUE THREAD

**Issue by orangecoder** [numbbbbb/atswift#2]
刚学nodejs，想找个实例来看看

**Comment by numbbbbb** [comment]
这几天在忙大会的事 只能简单说一下
这个其实不算nodejs项目 基本只是一个静态页面 要用的话就是npm install安装依赖 然后安装gulp 就可以了 HTML用jade写
css用stylus写

2016-01-08 15:10 GMT+08:00 xiaoping notifications@github.com:

> 刚学nodejs，想找个实例来看看
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/atConf/atswift/issues/2.

## 

https://github.com/numbbbbb

**Comment by orangecoder** [comment]
谢谢哈
